In [13]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
import numpy as np
b=np.array([i for i in range(10)])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
import numpy as np
c=np.array([i for i in range(0, 10,2 )])
c

array([0, 2, 4, 6, 8])

In [23]:
print('c.shape=',c.shape)
print('c.ndim=',c.ndim)
print('c.dtype=',c.dtype)
print('c.size=',c.size)
print('c.itemsize=',c.itemsize)

c.shape= (5,)
c.ndim= 1
c.dtype= int32
c.size= 5
c.itemsize= 4


In [29]:
a=np.array([23,45,67,7,2,30,34,82])
print('a = array('+str(a)+')')

a = array([23 45 67  7  2 30 34 82])


In [31]:
print('최댓값 :', a.max())
print('최솟값 :', a.min())
print('평균 :', a.mean())

최댓값 : 82
최솟값 : 2
평균 : 36.25


In [34]:
b=np.random.randint(0, 99, size=10)
print('최댓값 :', b.max())
print('최솟값 :', b.min())
print('평균 :', b.mean())

최댓값 : 95
최솟값 : 22
평균 : 56.5


In [36]:
c=np.append(a, b)
print('c =', c)

c = [23 45 67  7  2 30 34 82 52 22 77 44 90 78 37 26 95 44]


In [43]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,2,2],[2,2,2],[2,2,2]])
print('a\n',a)
print('b\n',b)

a
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [47]:
print('\n1. a+b\n', a+b)
print('\n2. a-b\n', a-b)
print('\n3. a*b\n', a*b)
print('\n4. a/b\n', a/b)
print('\n5. a@b\n', a@b)
print('\n6. a**2\n', a**2)


1. a+b
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

2. a-b
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

3. a*b
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

4. a/b
 [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]

5. a@b
 [[12 12 12]
 [30 30 30]
 [48 48 48]]

6. a**2
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [67]:
a1= np.full((3,3),2)
print('a1 =\n', a1)

a1 =
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [68]:
a2=np.arange(12)
print('a2 =', a2)

a2 = [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [69]:
a3=np.arange(3,51, 3)
print('a3 =', a3)

a3 = [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [70]:
a4=np.linspace(0,20,5)
print('a4 =',a4)

a4 = [ 0.  5. 10. 15. 20.]


In [71]:
a1=np.arange(1,13).reshape(2,6)
print('a1 =\n', a1)

a1 =
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [73]:
a2=np.arange(1,31).reshape(3,10)
print('a2 =\n', a2)

a2 =
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [74]:
a3=np.arange(1,31).reshape(6,5)
print('a3 =\n', a3)

a3 =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [75]:
a4=np.transpose(a3)
print('a4 =\n', a4)

a4 =
 [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [76]:
a=np.random.randint(1,100, 15).reshape(3,5)
print('a =\n',a)


a =
 [[24 94  3 74 93]
 [59 29  5 89 23]
 [11 60 18  9 43]]


In [80]:
print('a의 열방향 최댓값 :', a.max(axis=0))
print('a의 열방향 최솟값 :', a.min(axis=0))
print('a의 열방향 평균 :', a.mean(axis=0))

a의 열방향 최댓값 : [59 94 18 89 93]
a의 열방향 최솟값 : [11 29  3  9 23]
a의 열방향 평균 : [31.33333333 61.          8.66666667 57.33333333 53.        ]


In [81]:
print('a의 행방향 최댓값 :', a.max(axis=1))
print('a의 행방향 최솟값 :', a.min(axis=1))
print('a의 행방향 평균 :', a.mean(axis=1))

a의 행방향 최댓값 : [94 89 60]
a의 행방향 최솟값 : [3 5 9]
a의 행방향 평균 : [57.6 41.  28.2]


In [83]:
a=np.array([i for i in range(1,11)])
b=np.array([i for i in range(2,10,2)])
print('a =', a)
print('b =', b)

a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]


In [88]:
b=a[5:]
print('b =', b)
c=a[6:]
print('c =', c)
d=a[:3]
print('d =', d)
e=a[::2]
print('e =', e)
f=a[::-2]
print('f =', f)

b = [ 6  7  8  9 10]
c = [ 7  8  9 10]
d = [1 2 3]
e = [1 3 5 7 9]
f = [10  8  6  4  2]


In [139]:
a=np.arange(24).reshape(4,3,2)
print('index              element')
for i in range(4):
    for j in range(3):
        for k in range(2):
            print('({}, {}, {})             {}'.format(i, j ,k, a[i,j,k]))

index              element
(0, 0, 0)             0
(0, 0, 1)             1
(0, 1, 0)             2
(0, 1, 1)             3
(0, 2, 0)             4
(0, 2, 1)             5
(1, 0, 0)             6
(1, 0, 1)             7
(1, 1, 0)             8
(1, 1, 1)             9
(1, 2, 0)             10
(1, 2, 1)             11
(2, 0, 0)             12
(2, 0, 1)             13
(2, 1, 0)             14
(2, 1, 1)             15
(2, 2, 0)             16
(2, 2, 1)             17
(3, 0, 0)             18
(3, 0, 1)             19
(3, 1, 0)             20
(3, 1, 1)             21
(3, 2, 0)             22
(3, 2, 1)             23


In [140]:
np.concatenate((a[0,0], a[1,0]), axis=0)

array([0, 1, 6, 7])

In [141]:
np.concatenate((a[0,0], a[2,1]), axis=0)

array([ 0,  1, 14, 15])

In [142]:
np.concatenate((a[0],a[1]), axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [143]:
np.concatenate((a[0],a[1]), axis=1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [144]:
a=np.arange(16).reshape(4,4)
b=a[:,1]
print('b =', b)
c=a[2, 1:]
print('c =', c)
d=a[ :2, :2]
print('d =\n', d)
e=a[1:3, 1:3]
print('e =\n', e)

b = [ 1  5  9 13]
c = [ 9 10 11]
d =
 [[0 1]
 [4 5]]
e =
 [[ 5  6]
 [ 9 10]]


In [145]:
f=a[:2, :3].flatten()
print('f =', f)
g=a[2:, :].flatten()
print('g =', g)
h=a[1:4:2, 1:].flatten()
print('h =', h)

f = [0 1 2 4 5 6]
g = [ 8  9 10 11 12 13 14 15]
h = [ 5  6  7 13 14 15]


In [146]:
a=np.array([[1,1,-1],[2,-1,3],[1,2,1]], dtype=np.int32)
b=np.array([0,9,8])
c=np.linalg.solve(a,b)
print('x = {}, y = {}, z = {}'.format(c[0], c[1], c[2]))

x = 1.0000000000000007, y = 2.0, z = 2.9999999999999996


In [147]:
d=np.linalg.det(a)
print('det(A) =',d)

det(A) = -11.000000000000002


In [153]:
e=a[1:, 1:]
f=a[1:, 0:3:2]
g=a[1:, :2]
h=np.linalg.det(e)*a[0,0]-np.linalg.det(f)*a[0,1]+np.linalg.det(g)*a[0,2]
print('det(A) =',h)

det(A) = -11.000000000000002
